version: '3'
services:
  builder:
    command: 'ts-node-dev --transpile-only --respawn src/main.ts'
    build: builder/.
    working_dir: /home/node
    volumes:
      - ./builder/src/:/home/node/src/
