version: '3'
services:
  developmentserver:
    command: 'ts-node-dev --transpile-only --respawn main.ts'
    build: developmentServer/.
    working_dir: /home/node/src
    volumes:
      - ./developmentServer/src/:/home/node/src/
      - ./_resume/:/home/node/resume/
    environment:
      source_directory: '/home/node/resume/'
      log_level: 4
    ports:
      - '${DEVELOPMENT_SERVER_PORT}:3000'
      - '${RELOAD_SERVER_PORT}:3001'
  manager:
    build: revisionManager/.
    volumes:
      - ./_resume/:/project/resume/
      - ./revisionManager/entrypoint.py:/project/entrypoint.py
    entrypoint: ['python', '/project/entrypoint.py']
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_BUCKET_NAME
