version: '3'
services:
  builder:
    command: 'ts-node-dev --transpile-only --respawn main.ts'
    build: builder/.
    working_dir: /home/node/src
    volumes:
      - ./builder/src/:/home/node/src/
      - ./resume/:/home/node/resume/
    environment:
      server_port: 3000
      reload_port: 3001
      source_directory: '/home/node/resume/'
      log_level: 4
    ports:
    - 3000:3000
    - 3001:3001
  manager:
    build: manager/.
    volumes:
      - ./resume/:/project/resume/
      - ./manager/entrypoint.py:/project/entrypoint.py
    entrypoint: ['python', '/project/entrypoint.py']
