version: '3'
services:
  builder:
    command: 'ts-node-dev --transpile-only --respawn main.ts'
    build: builder/.
    working_dir: /home/node/src
    volumes:
      - ./builder/src/:/home/node/src/
      - ./resume/:/home/node/resume/
    environment:
      source_directory: '/home/node/resume/'
      log_level: 4
    ports:
      - '${DEVELOPMENT_SERVER_PORT}:3000'
      - '${RELOAD_SERVER_PORT}:3001'
  manager:
    build: manager/.
    volumes:
      - ./resume/:/project/resume/
      - ./manager/entrypoint.py:/project/entrypoint.py
    entrypoint: ['python', '/project/entrypoint.py']
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_BUCKET_NAME
  lambda:
    build: lambda
    command: 'tsc'
    working_dir: '/home/node'
    volumes:
      - ./lambda:/home/node
  render:
    build: render
    command: 'sh -c "tsc && npm pack"'
    working_dir: '/home/node'
    volumes:
      - ./render:/home/node

